/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const BRAND_COLORS = {
  primary: '#1E3A8A', // Blue
  secondary: '#F97316', // Orange
};

export const CATEGORIES = [
  'Cables',
  'Adapters',
  'Mics',
  'ICs & Semiconductors',
  'Passives',
  'Power Modules',
  'Battery & BMS',
  'Tools & Equipment',
  'Electromaal Labs',
];

export const MOCK_PRODUCTS = [
  {
    id: 'c1',
    name: 'Hyper-Core USB-C Ultra-Durable Cable (100W)',
    description: 'Industrial-grade Kevlar-shielded USB-C to USB-C cable. Designed for ultra-stable lab power transfers and rapid data synchronization.',
    price: 650,
    category: 'Cables',
    image: 'https://images.unsplash.com/photo-1589615224936-acc4b0959c99?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    reviews: 142,
    stock: 250,
    isFeatured: true,
    brand: 'Electromaal Core',
    badge: 'new' as const,
    specs: { wattage: '100W' }
  },
  {
    id: 'c2',
    name: 'Shield-Link Professional XLR Audio Cable',
    description: 'Balanced low-noise microphone and instrument cable with standard 3-pin solderless metal conductors for precise signal fidelity.',
    price: 950,
    category: 'Cables',
    image: 'https://images.unsplash.com/photo-1516223725307-6f76b9ec8742?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    reviews: 88,
    stock: 120,
    brand: 'Acoustic Shield',
    badge: '' as const,
    specs: {}
  },
  {
    id: 'a1',
    name: '65W Dual-Port GaN Intelligent Adapter',
    description: 'Ultra-compact Gallium Nitride power adapter delivering multi-voltage charging profiles up to 65W with thermal regulation sensors.',
    price: 1850,
    category: 'Adapters',
    image: 'https://images.unsplash.com/photo-1623150503004-e23e051834e2?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    reviews: 310,
    stock: 95,
    isFeatured: true,
    brand: 'Anker Tech',
    badge: 'discount' as const,
    discountPercent: 15,
    specs: { wattage: '65W' }
  },
  {
    id: 'a2',
    name: 'Nano-Core 20W USB-C Travel Adapter',
    description: 'Space-saving 20W high-speed charging brick optimized for robust handheld devices, battery boxes, and small lab instruments.',
    price: 850,
    category: 'Adapters',
    image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=800&auto=format&fit=crop',
    rating: 4.7,
    reviews: 440,
    stock: 180,
    brand: 'Baseus Volt',
    badge: 'new' as const,
    specs: { wattage: '20W' }
  },
  {
    id: 'a3',
    name: 'Pro-Load 100W Desktop Quad GaN Station',
    description: 'Expert-grade power delivery station with dynamic resource allocator across 3x USB-C and 1x USB-A high-amperage terminals.',
    price: 3450,
    category: 'Adapters',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    reviews: 67,
    stock: 45,
    brand: 'Electromaal Core',
    badge: '' as const,
    specs: { wattage: '100W' }
  },
  {
    id: 'm1',
    name: 'Electromaal Pro-Caster Condenser Microphone',
    description: 'Premium cardioid recording microphone with integrated pop filter, heavy-duty anti-vibration isolation mount, and direct USB hub output.',
    price: 5200,
    category: 'Mics',
    image: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800&auto=format&fit=crop',
    rating: 5.0,
    reviews: 58,
    stock: 30,
    isFeatured: true,
    brand: 'Electromaal Core',
    badge: 'new' as const,
    specs: {}
  },
  {
    id: 'm2',
    name: 'Broadcaster Studio USB Microphone',
    description: 'Direct monitoring professional studio-grade microphone with built-in zero-latency headphone output and gain selector controls.',
    price: 4900,
    category: 'Mics',
    image: 'https://images.unsplash.com/photo-1484972759836-b93f9ef2b293?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    reviews: 104,
    stock: 18,
    brand: 'Rode Audio',
    badge: 'discount' as const,
    discountPercent: 10,
    specs: {}
  },
  {
    id: '1',
    name: 'TP4056 Li-ion Charger Module',
    description: 'Micro-USB charging module with battery protection for 3.7V Li-ion cells. Highly efficient with onboard battery status LEDs.',
    price: 45,
    category: 'Power Modules',
    image: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    reviews: 1250,
    stock: 500,
    isFeatured: true,
  },
  {
    id: '2',
    name: 'XL6009 Boost Converter Module',
    description: 'High-performance step-up DC-DC converter module with adjustable output voltage potentiometer. Max 4A load current.',
    price: 120,
    category: 'Power Modules',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    rating: 4.7,
    reviews: 850,
    stock: 120,
    isFeatured: true,
  },
  {
    id: '3',
    name: 'T12 Digital Soldering Station',
    description: 'Premium soldering station featuring OLED display, extremely rapid 8 second heating, and smart precise temperature control limits.',
    price: 4500,
    category: 'Tools & Equipment',
    image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    reviews: 320,
    stock: 25,
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Electromaal Mini UPS (12V/2A)',
    description: 'Our custom-developed robust mini UPS for routers, modems, and small DIY projects. Delivers 4 hours backup with reliable BMS.',
    price: 1850,
    category: 'Electromaal Labs',
    image: 'https://images.unsplash.com/photo-1593344484962-796055d4a3a4?q=80&w=800&auto=format&fit=crop',
    rating: 5.0,
    reviews: 45,
    stock: 15,
    isFeatured: true,
  },
  {
    id: '5',
    name: 'ESP32-WROOM-32U Development Board',
    description: 'Dual-core WiFi + Bluetooth SoC with external IPEX antenna connector. Ideal for long-range smart home IoT hubs.',
    price: 550,
    category: 'ICs & Semiconductors',
    image: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    reviews: 640,
    stock: 200,
  },
  {
    id: '6',
    name: 'BMS 3S 40A Enhanced Version',
    description: 'Critical balance charge control safety module for custom 3-cell 18650 lithium battery packs. Protects against over-discharge.',
    price: 320,
    category: 'Battery & BMS',
    image: 'https://images.unsplash.com/photo-1591179064731-db3e288e7e1c?q=80&w=800&auto=format&fit=crop',
    rating: 4.6,
    reviews: 180,
    stock: 85,
  },
  {
    id: '7',
    name: 'LM2596S DC-DC Buck Converter',
    description: 'Adjustable step-down regulator supporting high efficiency. Output range 1.25V-30V with standard thermal shutdown safeguards.',
    price: 90,
    category: 'Power Modules',
    image: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=800&auto=format&fit=crop',
    rating: 4.5,
    reviews: 420,
    stock: 350,
  },
  {
    id: '8',
    name: 'M40 Soldering Iron Support Stand',
    description: 'All-metal cast-iron heavy duty base stand with sponge cleaner and brass spiral coil wire for safe lab operation.',
    price: 250,
    category: 'Tools & Equipment',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?q=80&w=800&auto=format&fit=crop',
    rating: 4.4,
    reviews: 95,
    stock: 50,
  },
  {
    id: '9',
    name: 'Atmega328P-PU with Optiboot',
    description: 'High performance, low power Microchip RISC 8-bit AVR microcontroller with pre-flashed Arduino bootloader. 28-pin DIP package.',
    price: 230,
    category: 'ICs & Semiconductors',
    image: 'https://images.unsplash.com/photo-1608564697071-419ab697f613?q=80&w=800&auto=format&fit=crop',
    rating: 4.9,
    reviews: 580,
    stock: 300,
    isFeatured: true,
  },
  {
    id: '10',
    name: 'Resistor Assortment Kit (300 Pcs)',
    description: 'High-quality 1/4W metal film resistors assort pack covering 30 common resistor values from 10 Ohm to 1M Ohm. Tolerances of 1%.',
    price: 180,
    category: 'Passives',
    image: 'https://images.unsplash.com/photo-1544256718-3bcf237f3974?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    reviews: 240,
    stock: 450,
  },
  {
    id: '11',
    name: 'Multipurpose Electrolytic Capacitors',
    description: 'Dynamic capacitor selection pack containing 120 polarized electrolytic capacitors from 1uF to 1000uF. Voltage ratings up to 50V.',
    price: 350,
    category: 'Passives',
    image: 'https://images.unsplash.com/photo-1601524909162-be87252be298?q=80&w=800&auto=format&fit=crop',
    rating: 4.7,
    reviews: 130,
    stock: 120,
  },
  {
    id: '12',
    name: 'Premium 18650 3.7V Battery Cell',
    description: 'High-capacity Grade-A rechargeable lithium battery cell with 2500mAh rating. Ideal for battery banks, robots, and portable gear.',
    price: 220,
    category: 'Battery & BMS',
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=800&auto=format&fit=crop',
    rating: 4.8,
    reviews: 740,
    stock: 600,
  },
  {
    id: '13',
    name: 'Electromaal IoT Weather Station',
    description: 'Premium customized IoT weather tracking module with onboard temperature, relative humidity, pressure, and solar UV index sensors.',
    price: 3600,
    category: 'Electromaal Labs',
    image: 'https://images.unsplash.com/photo-1590053132530-50ed147d2511?q=80&w=800&auto=format&fit=crop',
    rating: 5.0,
    reviews: 18,
    stock: 10,
    isFeatured: true,
  },
  {
    id: '14',
    name: 'Multi-turn Precision Potentiometer 10K',
    description: 'High-grade 3590S wirewound potentiometer with 10 full turns for precise analog resistance tuning. Fitted with dual-dial dial scale.',
    price: 190,
    category: 'Passives',
    image: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?q=80&w=800&auto=format&fit=crop',
    rating: 4.6,
    reviews: 74,
    stock: 180,
  },
  {
    id: '15',
    name: '4-Channel Logic Level Shifter',
    description: 'Bi-directional standard logic level translator safely stepping 5V microcontrollers down to modern 3.3V sensor communications.',
    price: 40,
    category: 'ICs & Semiconductors',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop',
    rating: 4.7,
    reviews: 110,
    stock: 400,
  },
  {
    id: '16',
    name: 'Digital Multimeter with Transistor Test',
    description: 'Handheld digital multimeter (DMM) with large clear LCD, testing standard AC/DC voltage, continuous audio alert, and triode testing.',
    price: 380,
    category: 'Tools & Equipment',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800&auto=format&fit=crop',
    rating: 4.5,
    reviews: 215,
    stock: 80,
  }
];
